# Perceptron implementation

# OR Gate

In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use('fivethirtyeight')

In [2]:
# ! pip install joblib

In [8]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

In [3]:

# df_OR = pd.DataFrame(np.array([[0,0,1,1], [0,1,0,1], [0,1,1,1]]),
#                    columns=['x1', 'x2', 'y'])

OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(data = OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [4]:
def prepare_data(df,target_col = 'y'):
    X = df.drop(target_col,axis = 1)
    y = df[target_col]
    
    return X,y


In [9]:
X,y = prepare_data(df_OR)
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA,epochs = EPOCHS)

model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10003527  0.10009458 -0.19987904]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.10003527  0.10009458 -0.09987904]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10003527 0.10009458 0.00012096]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: i

In [10]:
model_or.predict(X=[[1,1]])
model_or.predict(X=[[1,0]])

array([1])

In [42]:
p = Perceptron()

In [14]:
p.eta

In [16]:
p.epochs

In [17]:
p = Perceptron(eta = 0.01,epochs = 10)

In [18]:
p.eta

0.01

In [19]:
p.epochs

10

In [20]:
p.weights

array([ 1.14988683e-04,  8.62853317e-05, -1.73501436e-04])

In [22]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [43]:
p.fit(X,y)

X_with_bias =[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


TypeError: 'NoneType' object cannot be interpreted as an integer

In [38]:
np.where(34>0,1,0)

array(1)

In [39]:
np.where(-34>0,1,0)

array(0)

In [5]:
np.random.randn(3)

array([0.60644113, 1.71492484, 1.0982923 ])

In [ ]:
# lr = LinearRegression()
# lr.fit()

In [9]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [10]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.c_[X,-np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])