# Perceptron implementation

# OR Gate

In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use('fivethirtyeight')

In [2]:
# ! pip install joblib

In [32]:
class Perceptron:
    def __init__(self, eta: float = None, epochs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # Learning rate
        self.epochs = epochs # iterations
    
    def fit(self, X, y):
        self.X= X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X_with_bias ={X_with_bias}')
        

In [13]:
p = Perceptron()

In [14]:
p.eta

In [16]:
p.epochs

In [17]:
p = Perceptron(eta = 0.01,epochs = 10)

In [18]:
p.eta

0.01

In [19]:
p.epochs

10

In [20]:
p.weights

array([ 1.14988683e-04,  8.62853317e-05, -1.73501436e-04])

In [22]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [34]:
p.fit(X,y)

AttributeError: 'Perceptron' object has no attribute 'fit'

In [5]:
np.random.randn(3)

array([0.60644113, 1.71492484, 1.0982923 ])

In [ ]:
# lr = LinearRegression()
# lr.fit()

In [9]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [10]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.c_[X,-np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])